#!/bin/sh

cache_dir=$HOME/.cache/updates
pac_cache_file=$cache_dir/pacman_cache

mkdir -p $cache_dir

if [[ ! "$EUID" = 0 ]]; then
    sudo ls /root
fi

if [ ! -s $pac_cache_file ]
then
    echo "Creating cache..."
    pacman -Slq > $pac_cache_file
    echo "Done"
fi

cat $pac_cache_file | fzf --bind 'space:toggle' --reverse --multi --preview 'pacman -Si {1}' | xargs -ro pacman -S
