#!/bin/sh

rofi_command="rofi -kb-move-char-back Left,h\
                   -kb-move-char-forward Right,l\
                   -theme $HOME/.config/rofi/themes/menu/brightness.rasi"

## Icons
ICON_UP=""
ICON_DOWN=""
ICON_OPT=""

if [[ ! -f /bin/brightnessctl ]]
then
    errormsg "Please install 'brightnessctl'"
    exit 1
fi

xdotool key Mode_switch

row=1
options="$ICON_UP\n$ICON_OPT\n$ICON_DOWN"
while
    BNESS="$(brightnessctl get)"
    MAX="$(brightnessctl max)"
    PERC="$((BNESS*100/MAX))"
    BLIGHT=${PERC%.*}
    chosen="$(echo -e "$options" | $rofi_command -p " $BLIGHT% " -dmenu -selected-row $row)"

    case $chosen in
        $ICON_UP)
            brightnessctl -q set +10%
            row=0
            ;;
        $ICON_DOWN)
            brightnessctl -q set 10%-
            row=2
            ;;
        $ICON_OPT)
            brightnessctl -q set 70%
            row=1
            ;;
    esac
    [ "$chosen" = "$ICON_UP" ] || [ "$chosen" = "$ICON_DOWN" ]
do true; done
