#!/usr/bin/env bash

rofi_command="rofi -kb-move-char-back Left,h\
                   -kb-move-char-forward Right,l\
                   -theme $HOME/.config/rofi/themes/menu/brightness.rasi"

## Icons
ICON_UP=""
ICON_DOWN=""
ICON_OPT=""

if [[ ! -f /usr/bin/blight ]]
then
    errormsg "Please install 'blight'"
    exit 1
fi

DEVICE=$(ls /sys/class/backlight | head -n 1)
row=1

options="$ICON_UP\n$ICON_OPT\n$ICON_DOWN"
while
    BNESS="$(blight -d $DEVICE get brightness)"
    PERC="$(($BNESS*100/255))"
    BLIGHT=${PERC%.*}
    chosen="$(echo -e "$options" | $rofi_command -p " $BLIGHT% " -dmenu -selected-row $row)"
    case $chosen in
        $ICON_UP)
            blight -d $DEVICE set +10%
            row=0
            ;;
        $ICON_DOWN)
            blight -d $DEVICE set -10%
            row=2
            ;;
        $ICON_OPT)
            blight -d $DEVICE set 70%
            row=1
            ;;
    esac
    [ "$chosen" = "$ICON_UP" ] || [ "$chosen" = "$ICON_DOWN" ]
do true; done
