#!/bin/sh

rofi_command="rofi -kb-move-char-back Left,h\
                   -kb-move-char-forward Right,l\
                   -theme $HOME/.config/rofi/themes/menu/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=""
reboot=""
lock=""
suspend=""
logout=""

xdotool key Mode_switch

# Variable passed to rofi
options="$lock\n$reboot\n$shutdown\n$suspend\n$logout"
chosen="$(echo -e "$options" | $rofi_command -p " 祥  $uptime " -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        if [[ -f /usr/bin/i3lock ]]; then
            i3lock
        elif [[ -f /usr/bin/betterlockscreen ]]; then
            betterlockscreen -l
        fi
        ;;
    $suspend)
        # mpc -q pause
        # amixer set Master mute
        # systemctl suspend
        ;;
    $logout)
        awesome-client 'awesome.quit()'
        ;;
esac
