#!/bin/sh

rofi_command="rofi -kb-move-char-back Left,h\
                   -kb-move-char-forward Right,l\
                   -replace\
                   -theme $HOME/.config/rofi/themes/menu/screenshot.rasi"

scr_dir="$HOME/Pictures/screenshots"
mkdir -p "${scr_dir}"

getStamp()
{
    date '+%Y%m%d-%H%M%S'
}

if [[ ! -f /usr/bin/flameshot ]]
then
    errormsg "Please install 'flameshot'"
    exit 0
fi

# Options
screen=""
window=""
area=""
options="$window\n$screen\n$area"

xdotool key Mode_switch

chosen="$(echo -e "$options" | $rofi_command -p ' flameshot ' -dmenu -selected-row 1)"
sleep 0.25
case $chosen in
    $screen)
        scr_name=full-$(getStamp).png
        flameshot full -p ${scr_dir}/${scr_name}
        ;;
    $window)
        scr_name=window-$(getStamp).png
        position="$(xdotool getwindowfocus getwindowgeometry | grep Position | awk '{print $2}')"
        position_x="$(echo $position | awk 'BEGIN{FS=","} {print $1}')"
        position_y="$(echo $position | awk 'BEGIN{FS=","} {print $2}')"
        size="$(xdotool getwindowfocus getwindowgeometry | grep Geometry | awk '{print $2}')"
        flameshot full --region $(echo "$size+$position_x+$position_y") -p ${scr_dir}/${scr_name}
        ;;
    $area)
        window_focus=$(xdotool getwindowfocus)
        flameshot gui --path "$scr_dir" -r > /dev/null
        scr_path=$(find "$scr_dir" -type f -newermt `date --date='1 second ago' +%Y-%m-%dT%H:%M:%S` | head -n 1)
        scr_name=$(basename $scr_path)
        xdotool windowfocus $window_focus
        ;;
    *)
        exit 0
        ;;
esac

if [ -n "$scr_name" ]
then
    tmp_small_image=/tmp/screenshot_tmp
    convert $scr_dir/$scr_name -resize 100x60 $tmp_small_image
    notify-send -u normal -i $tmp_small_image \
                "Screenshot" "Screenshot save as $scr_name"
fi
